apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
  orphanedResources:
    warn: true
  sourceRepos:
    - 'git@github.com:mr-sour/embedded-toolbox-helm.git'
