apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: default
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: default
      server: 'https://kubernetes.default.svc'
  orphanedResources:
    warn: true
  sourceRepos:
    - 'git@github.com:PeopleNet/embedded-toolbox-helm.git'
